[workspace]
members = [
    "applied-config",
    "json-schema",
    "observability",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.96"
assertables = "9.5.0"
assert-json-diff = "2.0.2"
serde = "1.0.218"
serde_json = "1.0.139"
tokio = "1.44.1"
tracing = "0.1.41"
