[package]
name = "observability"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
valuable = { version = "0.1.1", features = ["derive"] }
valuable-serde = "0.1.1"
