[package]
name = "flexys-json-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
jsonschema = { version = "0.37.0", default-features = false } # disable all resolving
serde_json = { workspace = true }

[dev-dependencies]
assertables = { workspace = true }
assert-json-diff = { workspace = true }
